FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN maven clean package 

FROM eclipse-temurin:-17-jre
COPY --FROM=build /app/target/*.jar /app.jar
Expose 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
